CHPL_MAKE_HOME = /home/kp167/chap-svn

TMPDIRNAME = examples/resilience/sacevdir
BINNAME = cobegin2loc

TMPBINNAME = examples/resilience/sacevdir/cobegin2loc.tmp
COMP_GEN_CFLAGS = $(WARN_GEN_CFLAGS) $(IEEE_FLOAT_GEN_CFLAGS) 
COMP_GEN_LFLAGS = 
TAGS_COMMAND = -@which $(CHPL_TAGS_UTIL) > /dev/null 2>&1 && test -f $(CHPL_MAKE_HOME)/runtime/$(CHPL_TAGS_FILE) && cd examples/resilience/sacevdir && cp $(CHPL_MAKE_HOME)/runtime/$(CHPL_TAGS_FILE) . && $(CHPL_TAGS_UTIL) $(CHPL_TAGS_FLAGS) $(CHPL_TAGS_APPEND_FLAG) *.c *.h
CHPLSRC = \
	examples/resilience/sacevdir/_main.c \


LIBS =


include $(CHPL_MAKE_HOME)/runtime/etc/Makefile.exe


